### ISSUE TITLE
Previewing a new page does not work

### ISSUE THREAD

**Issue by elsueno** [keen-studio/react-wp-rest#10]
When I add a new page without publishing previewing that page does not work.

**Comment by jmikrut** [comment]
Good point.  We know exactly why this doesn't work and will plan to release a fix shortly.  It has to do with the fact that no route has yet been created - so React does not know what route to render.

**Comment by jmikrut** [comment]
And an update - you can now preview unpublished posts and pages. 

See ab4f84a.

Take a look!
