### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by madderlake** [keen-studio/react-wp-rest#12]
I'm loving this boilerplate and plan to use it as a start for a product app. 

I had this totally up and running, then shut down my computer (mac) and cannot load the site - connection is refused on :8080. The page loads at :3000, but cannot connect to the data. 

I am not sure where to start. Though I see this is a common problem after researching the issue, I want to look at it in the context of this boilerplate.

Thanks in advance!
<img width="884" alt="screen shot 2018-12-14 at 9 20 15 am" src="https://user-images.githubusercontent.com/1567081/50017641-8a3e4180-ff81-11e8-87a8-9234eb487662.png">

**Comment by jmikrut** [comment]
Gotta restart Docker!

`docker-compose start` within your API directory will get you up and running again!

**Comment by madderlake** [comment]
Thanks. I had tried that, and tried again just now, and getting white page with the above errors in console.

**Comment by jmikrut** [comment]
Hmm.. Can you access WP? If you go to `http://localhost:8080/wp-admin` - can you log in?

If so, can you hit this route within your browser? `http://localhost:8080/wp-json/react-wp-rest/pages/list`?

**Comment by jmikrut** [comment]
Any luck here?  I'd like to close the issue if this has been resolved, or help if it has not been resolved.

**Comment by madderlake** [comment]
Yes, I did need to restart Docker - but in the api. The docs make the docker command seem like an installation, not a command to start up the api. I'm new to Docker ;)
