### ISSUE TITLE
Database help - changed Site *and* Home address, now can't continue setup.

### ISSUE THREAD

**Issue by joshuaiz** [keen-studio/react-wp-rest#5]
Hello,

This looks amazing! Exactly what I was looking for.

I got everything up and running until the WordPress Configuration step. I entered in http://localhost:1337 for *both* the Site and Home urls which I don't think I was supposed to do. Whamp whomp.

Now I can't access the site to finish the other config steps. To fix, I trashed the project, created a new directory and tried to do all of the install steps again but it's still routing me to http://localhost:1337 and since I haven't run the build yet, there's nothing there.

I've tried restarting Docker and creating a new project from scratch but it seems like it is grabbing the old db no matter what I do.

Where is the Docker container and the WP db located so I can edit it manually? Or what else can I try?

Thanks!

**Comment by jmikrut** [comment]
Hey Joshua! 

Pumped that this repo has been of help to you.

We actually bundle in PHPMyAdmin to make editing the database super easy.  To access it, you can go to (by default) `http://localhost:8181` while Docker is up and running.

The username and pass are set in the `api/docker-compose.yml` file.

From there you should be able to do everything you need to with the database!

**Comment by joshuaiz** [comment]
@jmikrut Thanks for that. ...and I'm back in! I'll leave this open for now in case I run into anything else in the setup.

**Comment by joshuaiz** [comment]
Got everything sorted. Thanks again.
